version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  craft:
    build:
      context: .
    environment:
      DB_DSN: pgsql:host=db;port=5432;dbname=postgres
      DB_USER: postgres
      DB_PASSWORD: ''
      DB_SCHEMA: public
      DB_TABLE_PREFIX: ''
    ports:
      - '8080:80'
    volumes:
      - ./app:/app
      - composer:/composer
    depends_on: 
      - db
volumes:
  postgres:
  composer:

