version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    volumes:
      - ./.dockerdev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/usr/share/nginx
    ports:
      - "8080:80"
    depends_on:
      - fpm 
  fpm:
    build:
      dockerfile: ./.dockerdev/fpm.Dockerfile
      context: .
    environment: &php_environment
      DB_DSN: pgsql:host=db;port=5432;dbname=postgres
      DB_USER: postgres
      DB_PASSWORD: ''
      DB_SCHEMA: public
      DB_TABLE_PREFIX: ''
    volumes:
      - .:/usr/share/nginx
    depends_on: 
      - db
  php:
    build:
      context: .
    environment:
      <<: *php_environment
    volumes:
      - .:/usr/share/nginx
    depends_on:
      - db
volumes:
  postgres:

